# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Test

on:
  push:
    branches: ["test"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Enable firebase webframeworks
        run: firebase experiments:enable webframeworks
      - run: npm ci
      - name: Run npm ci in /functions
        working-directory: functions
        run: npm ci
      - name: Use test firebase project
        run: firebase use test
      - name: Deploy firebase project
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token "$FIREBASE_TOKEN"
